### ISSUE TITLE
There is no escape. Even when reading code.

### ISSUE THREAD

**Issue by roboboredom** [RyanModDev/EmuNO#1]
![image](https://github.com/RyanModDev/EmuNO/assets/57413665/b72f30e8-5087-4394-b5c1-b5fbd29dfcee)

sus...

**Comment by pandaninjas** [comment]
among us

**Comment by ryanccn** [comment]
among

**Comment by uncenter** [comment]
among us

**Comment by uncenter** [comment]
not planned????

![](https://cdn.discordapp.com/emojis/931744137982660628.webp?size=240&quality=lossless)
