### ISSUE TITLE
Curseforge support

### ISSUE THREAD

**Issue by zumbiepig** [RyanModDev/EmuNO#2]
Could you please upload this mod to Curseforge, please? If you upload this mod to Curseforge, it might be added to Fabulously Optimized. Fabulously Optimized is the NUMBER 1 modpack on Modrinth, and if this mod got included in Fabulously Optimized, your download count could increase by A LOT.
Disclaimer: I am not a dev of Fabulously Optimized, but I suggested it and they said if it was added to Curseforge, they might consider it.

**Comment by zumbiepig** [comment]
Never mind, I have uploaded this to Curseforge, reopen this issue if you want me to remove this from Curseforge. I can also split the Curseforge rewards (money) with you if you want. It is at [deleted link]
(Edit: Never mind, this was against the rules it has been deleted)

**Comment by ItsProfessional** [comment]
"split" Wow. Imagine taking 50% from something you haven't made or contributed to.

**Comment by ryanccn** [comment]
I appreciate the enthusiasm, but I don't think uploading a mod made by someone else without their permission is an appropriate course of action. Additionally, as [this comment](https://github.com/Fabulously-Optimized/fabulously-optimized/issues/732#issuecomment-1734797177) notes, it is against the CurseForge project policies.

**Comment by zumbiepig** [comment]
Yes, I just read the rules. I will delete the project from Curseforge right now. Can you please upload this to Curseforge though?

**Comment by ryanccn** [comment]
I will, at the appropriate juncture, in due course, in the fullness of time.

**Comment by Fnige** [comment]
> Fabulously Optimized is the NUMBER 1 modpack on Modrinth

Use adrenaline smh my head

**Comment by vgskye** [comment]
honestly yeah curseforge sucks

**Comment by zumbiepig** [comment]
I know Curseforge sucks, but Fabulously Optimized is better and updates faster. They said a mod needs to be on Curseforge and Modrinth to be added into the modpack

**Comment by ryanccn** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/emuno
